### ISSUE TITLE
코드 수정을 제안합니다.

### ISSUE THREAD

**Issue by N1ghtsky0** [spabucks/database#30]
https://github.com/spabucks/database/blob/b5c09b31035854370a6676123affc43577e7ced7/src/main/java/sphabucks/productimage/repository/IProductImageRepo.java#L10-L11

해당 코드를 아래와 같이 수정하는 것을 제안합니다.
```java
List<ProductImage> findAllByProductIdOrderByChk(Long productId);
```

**Comment by Ju-Yeongmin** [comment]
아 JPA에도 OrderBy 문법이 있구나 굿굿 찬성합니다
